-- ==============================================================================
-- PAKYÜREK KIRAATHANESİ - MEVCUT VERİLERİN SUPABASE AKTARIM DOSYASI
-- Tarih: 21.09.2026 15:23:14
-- Bu dosyayı Supabase Dashboard -> SQL Editor içerisine yapıştırıp "Run" butonuna basarak
-- mevcut tüm esnaf bakiyelerinizi, menüyü, masaları ve geçmişi anında yükleyebilirsiniz!
-- ==============================================================================

-- 1. KATEGORİLER (3 Adet)
INSERT INTO categories (id, name, icon, sort_order) VALUES (1, 'Çay & Sıcaklar', '☕', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;
INSERT INTO categories (id, name, icon, sort_order) VALUES (2, 'Kahveler', '🫖', 2) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;
INSERT INTO categories (id, name, icon, sort_order) VALUES (3, 'Soğuk Meşrubatlar', '🥤', 3) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;
SELECT setval('categories_id_seq', (SELECT COALESCE(MAX(id), 1) FROM categories));

-- 2. ÜRÜNLER VE FİYATLAR (20 Adet)
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (1, 1, 'Çay', 15, 10, '["Açık","Koyu","Duble","Paşa","Limonlu","Fincan"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (2, 1, 'Oralet (Portakal)', 15, 10, '["Sıcak","Ilık"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (3, 1, 'Oralet (Kivi)', 15, 10, '["Sıcak","Ilık"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (4, 1, 'Kuşburnu', 15, 10, '["Açık","Koyu","Duble","Paşa","Limonlu","Fincan"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (5, 1, 'Adaçayı', 15, 10, '["Limonlu","Ballı"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (6, 1, 'Ihlamur', 15, 10, '["Limonlu","Ballı"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (7, 1, 'Sıcak Süt', 20, NULL, '["Ballı","Şekerli","Sade"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (8, 1, 'Salep', 25, NULL, '["Bol Tarçınlı","Tarçınsız"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (9, 2, 'Türk Kahvesi', 30, NULL, '["Sade","Az Şekerli","Orta","Şekerli","Duble"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (10, 2, 'Dibek Kahvesi', 35, NULL, '["Sade","Az Şekerli","Orta","Şekerli","Duble"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (11, 2, 'Menengiç Kahvesi', 35, NULL, '["Sade","Az Şekerli","Orta","Şekerli","Duble"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (12, 2, 'Nescafe (3ü1 Arada)', 20, NULL, '["Sütlü","Sade"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (13, 3, 'Maden Suyu (Sade)', 15, NULL, '["Limonlu","Soğuk"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (14, 3, 'Meyveli Soda (Limon)', 18, NULL, '["Soğuk"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (15, 3, 'Meyveli Soda (Elma)', 18, NULL, '["Soğuk"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (16, 3, 'Kola', 30, NULL, '["Soğuk","Buzlu"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (17, 3, 'Fanta', 30, NULL, '["Soğuk","Buzlu"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (18, 3, 'Gazoz', 25, NULL, '["Soğuk","Limonlu"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (19, 3, 'Ayran', 20, NULL, '["Açık","Kapalı"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
INSERT INTO products (id, category_id, name, price, special_price, quick_notes, is_active) VALUES (20, 3, 'Su (Küçük)', 8, NULL, '["Soğuk","Oda Sıcaklığı"]', 1) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, price = EXCLUDED.price, special_price = EXCLUDED.special_price, quick_notes = EXCLUDED.quick_notes, is_active = EXCLUDED.is_active;
SELECT setval('products_id_seq', (SELECT COALESCE(MAX(id), 1) FROM products));

-- 3. MASALAR (30 Adet)
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (1, 'Masa 1', 'İçerisi', 'occupied', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (2, 'Masa 2', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (3, 'Masa 3', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (4, 'Masa 4', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (5, 'Masa 5', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (6, 'Masa 6', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (7, 'Masa 7', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (8, 'Masa 8', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (9, 'Masa 9', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (10, 'Masa 10', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (11, 'Masa 11', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (12, 'Masa 12', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (13, 'Masa 13', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (14, 'Masa 14', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (15, 'Masa 15', 'İçerisi', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (16, 'Bahçe 1', 'Bahçe', 'occupied', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (17, 'Bahçe 2', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (18, 'Bahçe 3', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (19, 'Bahçe 4', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (20, 'Bahçe 5', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (21, 'Bahçe 6', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (22, 'Bahçe 7', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (23, 'Bahçe 8', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (24, 'Bahçe 9', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (25, 'Bahçe 10', 'Bahçe', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (26, 'Dışarısı 1', 'Dışarısı', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (27, 'Dışarısı 2', 'Dışarısı', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (28, 'Dışarısı 3', 'Dışarısı', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (29, 'Dışarısı 4', 'Dışarısı', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
INSERT INTO tables (id, name, section, status, custom_tea_price, is_special) VALUES (30, 'Dışarısı 5', 'Dışarısı', 'empty', NULL, 0) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, section = EXCLUDED.section, custom_tea_price = EXCLUDED.custom_tea_price, is_special = EXCLUDED.is_special;
SELECT setval('tables_id_seq', (SELECT COALESCE(MAX(id), 1) FROM tables));

-- 4. ESNAFLAR VE VERESİYE BAKİYELERİ (5 Adet)
INSERT INTO merchants (id, name, shop_type, phone, notes, balance, created_at) VALUES (1, 'Berber Ahmet', 'Berber', '0555 111 2233', 'Çarşı İçi No: 4', 140, '2026-09-20 13:41:25') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, shop_type = EXCLUDED.shop_type, phone = EXCLUDED.phone, notes = EXCLUDED.notes, balance = EXCLUDED.balance;
INSERT INTO merchants (id, name, shop_type, phone, notes, balance, created_at) VALUES (2, 'Terzi Mehmet Usta', 'Terzi', '0555 222 3344', 'Pasaj İçi Kat 1', 90, '2026-09-20 13:41:25') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, shop_type = EXCLUDED.shop_type, phone = EXCLUDED.phone, notes = EXCLUDED.notes, balance = EXCLUDED.balance;
INSERT INTO merchants (id, name, shop_type, phone, notes, balance, created_at) VALUES (3, 'Kasap Veli', 'Kasap', '0555 333 4455', 'Köşe Dükkan', 250, '2026-09-20 13:41:25') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, shop_type = EXCLUDED.shop_type, phone = EXCLUDED.phone, notes = EXCLUDED.notes, balance = EXCLUDED.balance;
INSERT INTO merchants (id, name, shop_type, phone, notes, balance, created_at) VALUES (4, 'Merkez Eczanesi', 'Eczane', '0555 444 5566', 'Sağlık Ocağı Karşısı', 60, '2026-09-20 13:41:25') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, shop_type = EXCLUDED.shop_type, phone = EXCLUDED.phone, notes = EXCLUDED.notes, balance = EXCLUDED.balance;
INSERT INTO merchants (id, name, shop_type, phone, notes, balance, created_at) VALUES (5, 'Meydan Taksi Durağı', 'Taksi', '0555 555 6677', 'Durağın İçi', 180, '2026-09-20 13:41:25') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, shop_type = EXCLUDED.shop_type, phone = EXCLUDED.phone, notes = EXCLUDED.notes, balance = EXCLUDED.balance;
SELECT setval('merchants_id_seq', (SELECT COALESCE(MAX(id), 1) FROM merchants));

-- 5. ESNAF ÇETELE HAREKETLERİ (5 Adet)
INSERT INTO merchant_transactions (id, merchant_id, type, amount, description, payment_type, waiter_name, created_at) VALUES (1, 1, 'order', 140, 'Açılış Çetele Bakiyesi', 'nakit', 'Sistem', '2026-09-20 16:41:25') ON CONFLICT (id) DO NOTHING;
INSERT INTO merchant_transactions (id, merchant_id, type, amount, description, payment_type, waiter_name, created_at) VALUES (2, 2, 'order', 90, 'Açılış Çetele Bakiyesi', 'nakit', 'Sistem', '2026-09-20 16:41:25') ON CONFLICT (id) DO NOTHING;
INSERT INTO merchant_transactions (id, merchant_id, type, amount, description, payment_type, waiter_name, created_at) VALUES (3, 3, 'order', 250, 'Açılış Çetele Bakiyesi', 'nakit', 'Sistem', '2026-09-20 16:41:25') ON CONFLICT (id) DO NOTHING;
INSERT INTO merchant_transactions (id, merchant_id, type, amount, description, payment_type, waiter_name, created_at) VALUES (4, 4, 'order', 60, 'Açılış Çetele Bakiyesi', 'nakit', 'Sistem', '2026-09-20 16:41:25') ON CONFLICT (id) DO NOTHING;
INSERT INTO merchant_transactions (id, merchant_id, type, amount, description, payment_type, waiter_name, created_at) VALUES (5, 5, 'order', 180, 'Açılış Çetele Bakiyesi', 'nakit', 'Sistem', '2026-09-20 16:41:25') ON CONFLICT (id) DO NOTHING;
SELECT setval('merchant_transactions_id_seq', (SELECT COALESCE(MAX(id), 1) FROM merchant_transactions));

-- 6. GARSONLAR (4 Adet)
INSERT INTO waiters (id, name, created_at) VALUES (1, 'Yusuf', '2026-09-20 17:58:40') ON CONFLICT (id) DO NOTHING;
INSERT INTO waiters (id, name, created_at) VALUES (2, 'Muhammed', '2026-09-20 17:58:40') ON CONFLICT (id) DO NOTHING;
INSERT INTO waiters (id, name, created_at) VALUES (3, 'Mehmet Salih', '2026-09-20 17:58:40') ON CONFLICT (id) DO NOTHING;
INSERT INTO waiters (id, name, created_at) VALUES (4, 'Ahmet', '2026-09-20 17:58:40') ON CONFLICT (id) DO NOTHING;
SELECT setval('waiters_id_seq', (SELECT COALESCE(MAX(id), 1) FROM waiters));

-- 7. KASA VE ÖDEMELER GEÇMİŞİ (2 Adet)
INSERT INTO payments (id, table_id, table_name, amount, payment_type, waiter_name, created_at) VALUES (1, 1, 'Masa 1', 50, 'nakit', 'Kasa', '2026-09-19 02:13:11') ON CONFLICT (id) DO NOTHING;
INSERT INTO payments (id, table_id, table_name, amount, payment_type, waiter_name, created_at) VALUES (2, 16, 'Bahçe 1', 90, 'nakit', 'Kasa', '2026-09-19 02:27:50') ON CONFLICT (id) DO NOTHING;
SELECT setval('payments_id_seq', (SELECT COALESCE(MAX(id), 1) FROM payments));

-- 8. SİPARİŞLER (6 Adet)
INSERT INTO orders (id, table_id, table_name, waiter_name, status, total_amount, created_at, updated_at) VALUES (1, 1, 'Masa 1', 'Ahmet', 'completed', 50, '2026-09-19 02:12:25', '2026-09-19 02:13:11') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, table_id, table_name, waiter_name, status, total_amount, created_at, updated_at) VALUES (2, 16, 'Bahçe 1', 'Garson 1', 'completed', 108, '2026-09-19 02:26:21', '2026-09-19 02:26:36') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, table_id, table_name, waiter_name, status, total_amount, created_at, updated_at) VALUES (3, 16, 'Bahçe 1', 'Garson 1', 'completed', 90, '2026-09-19 02:27:30', '2026-09-19 02:27:50') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, table_id, table_name, waiter_name, status, total_amount, created_at, updated_at) VALUES (4, 16, 'Bahçe 1', 'Garson 1', 'pending', 105, '2026-09-19 02:45:01', '2026-09-19 02:45:01') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, table_id, table_name, waiter_name, status, total_amount, created_at, updated_at) VALUES (5, 1, 'Masa 1', 'Ahmet', 'approved', 30, '2026-09-19 02:58:05', '2026-09-19 02:58:05') ON CONFLICT (id) DO NOTHING;
INSERT INTO orders (id, table_id, table_name, waiter_name, status, total_amount, created_at, updated_at) VALUES (7, 1, 'Masa 1', 'Yusuf', 'cancelled', 20, '2026-09-21 11:35:21', '2026-09-21 11:35:33') ON CONFLICT (id) DO NOTHING;
SELECT setval('orders_id_seq', (SELECT COALESCE(MAX(id), 1) FROM orders));

-- 9. SİPARİŞ KALEMLERİ (8 Adet)
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (1, 1, 1, '�ay', 2, 10, '1 A�ik, 1 Koyu', 'ready') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (2, 1, 9, 'T�rk Kahvesi', 1, 30, 'Orta Sekerli', 'ready') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (3, 2, 5, 'Adaçayı', 4, 15, '', 'completed') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (4, 2, 3, 'Oralet (Kivi)', 4, 12, '', 'completed') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (5, 3, 9, 'Türk Kahvesi', 3, 30, '', 'ready') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (6, 4, 5, 'Adaçayı', 7, 15, '', 'pending') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (7, 5, 1, '�ay', 3, 10, 'A�ik', 'approved') ON CONFLICT (id) DO NOTHING;
INSERT INTO order_items (id, order_id, product_id, product_name, quantity, unit_price, note, status) VALUES (9, 7, 1, 'Çay', 2, 10, 'Açık', 'cancelled') ON CONFLICT (id) DO NOTHING;
SELECT setval('order_items_id_seq', (SELECT COALESCE(MAX(id), 1) FROM order_items));

